name: Doxygen Generation
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake doxygen graphviz ninja-build gfortran
    - uses: actions/checkout@v4
    - name: Cmake Configure
      run: cmake --preset ci
    - name: Generate Doxygen
      run: cmake --build --preset ci --target doxygen
    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Deploy
      if: github.repository == 'forestclaw/forestclaw'
      uses: peaceiris/actions-gh-pages@v4
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: forestclaw/forestclaw.github.io
        publish_branch: main
        publish_dir: ./build/doxygen/html
        destination_dir: docs/${{ steps.extract_branch.outputs.branch }}